### ISSUE TITLE
Increase amount of questions

### ISSUE THREAD

**Issue by Yeisoldt** [IMISE/snik-quiz#9]
I haven't done the maths, but since there will be a competitive event with approx. 100 users the amount of questions should be increased in order to avoid ties for the upper places. Maybe 15 or 20ish instead of 10.

**Comment by KonradHoeffner** [comment]
The math seem to be very complicated for this problem. Assuming random answers and disregarding different combinations with the same sum (so we get a lower bound), using the formula for the multiset coefficient https://en.wikipedia.org/wiki/Multiset#Counting_multisets (n+k+1) over (k) with k=4, and then using the birthday paradox formula, we arrive at the following probabilities (we only have 40 students AFAIK):

|n| # combinations  | collision 40 students | collision 100 students |
| ------------- | ------------- | ------------- |-------------------|
| 10 |1365   | 43%   | 97.6% |
| 15 |  4845 |   15% | 64%|
| 20 |  12650 |   6% | 32%|


Accounting for the different number of multiset sums would give a higher number. Also this counts any colision, not the top one. I would be interested in the solution method but I don't have the time for this unfortunately. But if we can use this in a SNIK quiz paper maybe we can justify the time spent.

**Comment by KonradHoeffner** [comment]
On second thought, it seems that *all* scores up to the maximum of n*11 seem to be reachable, except the scores 1 and 3 so I think the number of sums is n*11-2.
The tables then are:

**Comment by KonradHoeffner** [comment]
Thus I will use higher scores: 23, 11, 5 and 0.
